/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/_home'
import { Route as HomeIndexRouteImport } from './routes/_home.index'
import { Route as WritingSlugRouteImport } from './routes/writing/$slug'
import { Route as HomeIndexWritingSlugRouteImport } from './routes/_home.index.writing.$slug'

const HomeRoute = HomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const WritingSlugRoute = WritingSlugRouteImport.update({
  id: '/writing/$slug',
  path: '/writing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexWritingSlugRoute = HomeIndexWritingSlugRouteImport.update({
  id: '/index/writing/$slug',
  path: '/index/writing/$slug',
  getParentRoute: () => HomeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/writing/$slug': typeof WritingSlugRoute
  '/': typeof HomeIndexRoute
  '/index/writing/$slug': typeof HomeIndexWritingSlugRoute
}
export interface FileRoutesByTo {
  '/writing/$slug': typeof WritingSlugRoute
  '/': typeof HomeIndexRoute
  '/index/writing/$slug': typeof HomeIndexWritingSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_home': typeof HomeRouteWithChildren
  '/writing/$slug': typeof WritingSlugRoute
  '/_home/': typeof HomeIndexRoute
  '/_home/index/writing/$slug': typeof HomeIndexWritingSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/writing/$slug' | '/' | '/index/writing/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/writing/$slug' | '/' | '/index/writing/$slug'
  id:
    | '__root__'
    | '/_home'
    | '/writing/$slug'
    | '/_home/'
    | '/_home/index/writing/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRoute: typeof HomeRouteWithChildren
  WritingSlugRoute: typeof WritingSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/writing/$slug': {
      id: '/writing/$slug'
      path: '/writing/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof WritingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/index/writing/$slug': {
      id: '/_home/index/writing/$slug'
      path: '/index/writing/$slug'
      fullPath: '/index/writing/$slug'
      preLoaderRoute: typeof HomeIndexWritingSlugRouteImport
      parentRoute: typeof HomeRoute
    }
  }
}

interface HomeRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute
  HomeIndexWritingSlugRoute: typeof HomeIndexWritingSlugRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
  HomeIndexWritingSlugRoute: HomeIndexWritingSlugRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRouteWithChildren,
  WritingSlugRoute: WritingSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
